### ISSUE TITLE
snunlp/KR-Medium huggingface hub에 vocab.txt이 원래 vocab과 다릅니다.

### ISSUE THREAD

**Issue by bzantium** [snunlp/KR-Medium#1]
아래 코드를 사용하면 자동으로 hub에서 토크나이저 관련 파일이 다운로드되고 거기에는 vocab.txt 파일도 존재합니다.
tokenizer = AutoTokenizer.from_pretrained("snunlp/KR-Medium", do_lower_case=False)

하지만 이를 가지고 돌렸을 때 결과 값이 매우 저조하여 살펴보니 vocab.txt 파일이 본 repository에 올려주신 20000-vocab.txt과 상이한 것을 발견하였고 vocab.txt 파일을 20000-vocab.txt의 값으로 바꿔주니 정상적으로 작동하였습니다.

한 번 hub에 올려두신 파일을 살펴봐 주시면 좋을 것 같습니다.

감사합니다.

**Comment by snunlp** [comment]
안녕하세요,
현재 github에 올라와 있는 20000-vocab.txt 파일이 맞는 것이고, 이에 따라 huggingface에 올라간 파일을 수정하고 있습니다.
감사합니다.
